spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&time_zone=+1:00
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
liquibase:
  change-log: config/liquibase/master.xml
  drop-first: true
  default-schema:
mybatis:
  configuration:
    map-underscore-to-camel-case: true
